# Generated by Django 5.2.1 on 2025-06-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0008_alter_post_managers'),
        ('app_users', '0010_alter_profile_nickname_alter_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='app_users.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app_users.profile'),
        ),
    ]
