# Generated by Django 5.2.1 on 2025-06-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0010_tag_post_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
