# Generated by Django 5.2.1 on 2025-06-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0011_rename_tag_tags_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='blog_app_category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='blog_app_comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_app_post',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='blog_app_tags',
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blogs.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blogs.tags')),
            ],
            options={
                'db_table': 'blog_app_post_tags',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='app_blogs.PostTags', to='app_blogs.tags'),
        ),
    ]
