# Generated by Django 5.2.1 on 2025-06-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0012_alter_category_table_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
        migrations.AlterModelTable(
            name='posttags',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tags',
            table=None,
        ),
    ]
