# Generated by Django 5.2.1 on 2025-06-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0013_alter_category_table_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='app_blogs.tags'),
        ),
        # migrations.DeleteModel(
        #     name='PostTags',
        # ),
    ]
