# Generated by Django 5.2.1 on 2025-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0014_alter_post_tags_delete_posttags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('un_published', 'Un_published'), ('archived', 'Archived'), ('on_moderation', 'On_moderation'), ('approved', 'Approved'), ('not_approved', 'not_approved'), ('deleted', 'Deleted')], default='draft'),
        ),
    ]
