version: '3.8'

services:
  hello_django:
    build: .
    container_name: hello_django_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: 
      bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8001"


  db:
    image: postgres:17
    container_name: hello_django_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

