# Generated by Django 5.2.1 on 2025-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_profile_email_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
