# Generated by Django 5.2.1 on 2025-06-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0013_alter_profile_email_alter_profile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='django_app_profile',
        ),
    ]
