# Generated by Django 5.2.1 on 2025-06-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
