# Generated by Django 5.2.1 on 2025-06-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
