# Generated by Django 5.2.1 on 2025-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
