# Generated by Django 5.2.1 on 2025-06-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_category_post_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
